services:
  - type: web
    name: prelux-ecommerce
    env: node
    buildCommand: npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: SERVER_URL
        value: https://prelux-store.onrender.com
      - key: RENDER_EXTERNAL_URL
        value: https://prelux-store.onrender.com
